### ISSUE TITLE
ParseUnits rounds values so wrong amount

### ISSUE THREAD

**Issue by jimmylies** [dusaprotocol/sdk#3]
It arrives that parseUnits round down so here is an example in the case of increase allowance and swap :
"0.02770157345436614**9**" in the TokenInput
2770157345436614**8**n after parseUnits
So the allowance will be 2770157345436614**8**n
And for the swap, fetchBestTrade returns 2770157345436614**9**n so the tx fails because of insufficient allowance

**Comment by JoeTheCookie217** [comment]
[here](https://github.com/wevm/viem/blob/5a015273a8868efb82640005c0bb18acfa134c1b/src/utils/unit/parseUnits.ts) is viem implementation
it handles more complex cases

**Comment by JoeTheCookie217** [comment]
fixed in b52001178bd00fc1121136cd50d5dca546cbe9a6
update to 0.4.29
